---
title: "Weight Analysis"
author: "Simon Thornewill von Essen"
date: "7 2 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("rjags")
library("coda")
library("ggplot2")
library("reshape2")

setwd("C:\\Users\\SimonThornewill\\Documents\\Coursera_U-of-SC_Bayesian-Stats\\02_techniques-models\\week_5_project")
```

## Import Data

```{r}
df <- read.csv("./dat/RENPHO-Simon_clean.csv")

# Set Factors
df$month <- as.factor(df$month)
df$week_of_year <- as.factor(df$week_of_year)

head(df, 3)

```

## Graphical Exploration of Data

```{r}
ggplot(data=df, aes(x=mass_kg, y=body_fat_perc, alpha=0.6)) + 
  geom_point() + 
  xlab("Body Weight (KG)") + 
  ylab("Body Fat (%)")+
  ggtitle("Body Fat % vs. body weight in KG") + 
  theme(legend.position = "none") + 
  ggsave("./plots/01_bf_vs_bw.png",
         dpi="retina",
         width = 10,
         height = 6)
```

```{r}
ggplot(data=df, aes(x=month, y=mass_kg, fill=month)) + 
  geom_boxplot() + 
  ylab("Body Weight (KG)") + 
  xlab("Month of Year")+
  ggtitle("Month over Month Change in Body Weight (KG)") + 
  guides(fill=guide_legend(title="Month of Year"))+ 
  ggsave("./plots/02_bw_vs_mnth.png",
       dpi="retina",
       width = 10,
       height = 6)
```

```{r}

ggplot(data=df, aes(x=week_of_year, y=mass_kg, fill=week_of_year)) + 
  geom_boxplot() + 
  ylab("Body Weight (KG)") + 
  xlab("Week of Year")+
  ggtitle("Week over Week Change in Body Weight (KG)") + 
  guides(fill=guide_legend(title="Week of Year"))+ 
  ggsave("./plots/03_bw_vs_wk.png",
       dpi="retina",
       width = 10,
       height = 6)

```

## Modeling in JAGS

### Model Postulation


```{r}
mod1_string <- "model{
  for(i in 1:length(y)){
    y[i] ~ dnorm(mu[month[i]], prec)
  }
  
  for(j in 1:max(month)){
    mu[j] ~ dnorm(0.0, 1/1.0e6)
  }
  
  prec ~ dgamma(1.0/2.0, 1.0*1.0/2.0)
  sig = sqrt(1.0 / prec)
}"

data1_jags <- list(y=df$mass_kg, month=df$month)

params1 <- c("mu", "sig")

mod1 <- jags.model(textConnection(mod1_string), data=data1_jags, n.chains=3)
update(mod1, 1e3)

mod1_sim <- coda.samples(mod1, variable.names=params1, 1e3)
mod1_csim <- as.mcmc(do.call(rbind, mod1_sim))

png(file="./plots/04_chains_ANOVA.png")
plot(mod1_sim)
dev.off()

plot(mod1_sim)
```


### Convergence Diagnostics

```{r}
gelman.diag(mod1_sim)
```

```{r}
autocorr.diag(mod1_csim)
```

```{r}
png(file="./plots/05_autocorr.png")
autocorr.plot(mod1_csim)
dev.off()

autocorr.plot(mod1_csim)
```

```{r}
effectiveSize(mod1_csim)
```

```{r}
dic.samples(mod1, 1e3)
```

## Tests for Assumptions

### Residual Analysis

```{r}
pm_params <- colMeans(mod1_csim)

pm_params
```

```{r}
yhat <- pm_params[1:3][data1_jags$month]
resid <- data1_jags$y - yhat

df_resid <- data.frame(yhat=yhat, resid=resid, y=data1_jags$y, cat=factor(data1_jags$month))

ggplot(data = df_resid, aes(x=(1:nrow(df_resid)), y=resid, color=cat)) +
  geom_point() +
  ggtitle("Residuals") +
  xlab("Observation Number") +
  ylab("Residual") +
  ggsave("./plots/06_mod1_resid_1.png",
     dpi="retina",
     width = 10,
     height = 6)
```

```{r}
ggplot(data = df_resid, aes(x=yhat, y=resid)) +
  geom_point(aes(color=cat)) +
  ggtitle("Residuals for each group") + 
  ggsave("./plots/06_mod1_resid_2.png",
   dpi="retina",
   width = 10,
   height = 6)
```

### Alternative Models

```{r}
mod2_string <- "model{
  for(i in 1:length(y)){
    y[i] ~ dnorm(mu[month[i]], prec[month[i]])
  }
  
  for(j in 1:max(month)){
    mu[j] ~ dnorm(0.0, 1/1.0e6)
    prec[j] ~ dgamma(1.0/2.0, 1.0*1.0/2.0)
    sig[j] = sqrt(1.0 / prec[j])
  }
}"


mod2 <- jags.model(textConnection(mod2_string), data=data1_jags, n.chains=3)
update(mod2, 1e3)

mod2_sim <- coda.samples(mod2, variable.names=params1, 1e3)
mod2_csim <- as.mcmc(do.call(rbind, mod2_sim))

png(file="./plots/04_chains_ANOVA_2.png")
plot(mod2_sim)
dev.off()

plot(mod2_sim)
```

```{r}
dic1 <- dic.samples(mod1, 1e3)
dic2 <- dic.samples(mod2, 1e3)

dic1

dic2

```


## Posterior Summaries

```{r}
mean(mod2_csim[,1] > mod2_csim[,2])
```

```{r}
summary(mod2_sim)
```


```{r}
df_post <- as.data.frame(mod2_csim)
df_post$id <- seq(1:length(df_post))

head(df_post, 3)
```

```{r}
long <- melt(df_post[, c(1, 2, 5)], id.vars="id")

head(long)
```


```{r}
ggplot(long, aes(x=value, fill=variable)) +
  geom_density() + 
  ylab("Posterior Probability Density") + 
  xlab("Weight (Kg)") +
  guides(fill=guide_legend(title="Month of Year"))+ 
  ggtitle("Visualisation of Posterior Probability Density for Mean Weights betw. Months") + 
  ggsave("./plots/07_post_dist_weights.png",
     dpi="retina",
     width = 10,
     height = 6)
```
